#!/bin/bash
clear
echo Here is the list of installed Flatpak packages:
#ls /var/lib/flatpak/app
flatpak list
echo Which program would you like to run?

read varname

flatpak run $varname
## based on the following tutorial: https://ryanstutorials.net/bash-scripting-tutorial/bash-input.php
